services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: trophyhunters_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 121067
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django:
    build: .
    container_name: django_app
    command: >
      sh -c "python3 manage.py makemigrations &&
           python3 manage.py migrate &&
           python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - URL_GAME_DETAILS=http://store.steampowered.com/api/appdetails/
      - URL_GAME_LIST=http://api.steampowered.com/ISteamApps/GetAppList/v2
      - URL_TROPHY_LIST=http://api.steampowered.com/ISteamUserStats/GetSchemaForGame/v2
      - URL_GAME_NEWS=http://api.steampowered.com/ISteamNews/GetNewsForApp/v0002/
      - URL_USER_GAMES=http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/
      - URL_USER_GAME_TROPHIES=http://api.steampowered.com/ISteamUserStats/GetPlayerAchievements/v0001/
      - URL_USER_STEAMID=http://api.steampowered.com/ISteamUser/ResolveVanityURL/v0001/
      - STEAM_API_KEY=0C9B3284FF23E09B75F8F2FCAEA78C48
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DJANGO_SECRET_KEY=django-insecure-khd@m1xs(92q)1etkp9$v$uv%&8kewkkb7nbvnjea5*53m!7@=
      - DEBUG=1
      - DB_NAME=trophyhunters_db
      - DB_USER=admin
      - DB_PASSWORD=121067
      - DB_HOST=db
      - DB_PORT=5432
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`api.trophyhunters.tech`)"
      - "traefik.http.routers.django.entrypoints=websecure"
      - "traefik.http.routers.django.tls.certresolver=letsencrypt"

  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.trophyhunters.tech`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"

  redis:
    image: redis:7
    container_name: redis

  celery_fast:
    build: .
    container_name: celery-fast
    command: celery -A config worker --queues=fast --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - django
    environment:
      - URL_GAME_DETAILS=http://store.steampowered.com/api/appdetails/
      - URL_GAME_LIST=http://api.steampowered.com/ISteamApps/GetAppList/v2
      - URL_TROPHY_LIST=http://api.steampowered.com/ISteamUserStats/GetSchemaForGame/v2
      - URL_GAME_NEWS=http://api.steampowered.com/ISteamNews/GetNewsForApp/v0002/
      - URL_USER_GAMES=http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/
      - URL_USER_GAME_TROPHIES=http://api.steampowered.com/ISteamUserStats/GetPlayerAchievements/v0001/
      - URL_USER_STEAMID=http://api.steampowered.com/ISteamUser/ResolveVanityURL/v0001/
      - STEAM_API_KEY=0C9B3284FF23E09B75F8F2FCAEA78C48
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DJANGO_SECRET_KEY=django-insecure-khd@m1xs(92q)1etkp9$v$uv%&8kewkkb7nbvnjea5*53m!7@=

  celery_slow:
    build: .
    container_name: celery-slow
    command: celery -A config worker --queues=slow --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - django
    environment:
      - URL_GAME_DETAILS=http://store.steampowered.com/api/appdetails/
      - URL_GAME_LIST=http://api.steampowered.com/ISteamApps/GetAppList/v2
      - URL_TROPHY_LIST=http://api.steampowered.com/ISteamUserStats/GetSchemaForGame/v2
      - URL_GAME_NEWS=http://api.steampowered.com/ISteamNews/GetNewsForApp/v0002/
      - URL_USER_GAMES=http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/
      - URL_USER_GAME_TROPHIES=http://api.steampowered.com/ISteamUserStats/GetPlayerAchievements/v0001/
      - URL_USER_STEAMID=http://api.steampowered.com/ISteamUser/ResolveVanityURL/v0001/
      - STEAM_API_KEY=0C9B3284FF23E09B75F8F2FCAEA78C48
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DJANGO_SECRET_KEY=django-insecure-khd@m1xs(92q)1etkp9$v$uv%&8kewkkb7nbvnjea5*53m!7@=

  celery-beat:
    build: .
    container_name: celery-beat
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - django
    environment:
      - URL_GAME_DETAILS=http://store.steampowered.com/api/appdetails/
      - URL_GAME_LIST=http://api.steampowered.com/ISteamApps/GetAppList/v2
      - URL_TROPHY_LIST=http://api.steampowered.com/ISteamUserStats/GetSchemaForGame/v2
      - URL_GAME_NEWS=http://api.steampowered.com/ISteamNews/GetNewsForApp/v0002/
      - URL_USER_GAMES=http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/
      - URL_USER_GAME_TROPHIES=http://api.steampowered.com/ISteamUserStats/GetPlayerAchievements/v0001/
      - URL_USER_STEAMID=http://api.steampowered.com/ISteamUser/ResolveVanityURL/v0001/
      - STEAM_API_KEY=0C9B3284FF23E09B75F8F2FCAEA78C48
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DJANGO_SECRET_KEY=django-insecure-khd@m1xs(92q)1etkp9$v$uv%&8kewkkb7nbvnjea5*53m!7@=

volumes:
  postgres_data: