name: Sync frontend and backend

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para acceder a otras ramas

      - name: Checkout frontend branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout frontend || git checkout --orphan frontend
          git add .
          git commit -m "Sync frontend from dev" || echo "No changes to commit"
          git push origin frontend --force